org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.1.2
minecraft_version_range=[26.1, 26.2)
neo_version=26.1.2.72
neo_version_range=[26.1.2.29-beta,)
loader_version_range=[4,)

mod_id=retrofactorymanager
mod_name=Retro Factory Manager
mod_license=MIT
mod_version=1.0.3
mod_group_id=com.breakinblocks.retrofactorymanager
mod_authors=Saereth
mod_description=A visual blueprint-style program editor for Super Factory Manager.

sfm_version=4.34.0
sfm_version_range=[4.34,)
sfm_modrinth_version_id=tAxE7U7F

curseforge_project_id=1632863
modrinth_project_id=cYQ7WdVe

client_width=1920
client_height=1080
